import { GiftData } from './types';

export const initialGiftData: GiftData = {
  partnerName: 'My Player 2',
  senderName: 'Your Duo Forever',
  partnerNickname: 'My Favorite Girl',
  anniversaryDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(), // Exactly 1 month (30 days) ago
  welcomeGreeting: 'To my favorite duo partner, my late-night comfort, and the girl across my screen who stole my entire heart...',
  loveLetter: {
    title: 'Level 1 Complete: Happy 1-Month Anniversary',
    writtenDate: 'Written for our 1-Month Milestone',
    sealColor: '#e11d48', // deep rose
    content: `My dearest,

It has only been one month since you came into my life, but looking back at my days before you, it honestly feels like I was living in black and white.

People always say long distance is hard, and that miles create barriers. But the truth is, with you, miles feel like nothing at all. When your Instagram messages light up my screen, when we stay up until 4:00 AM texting back and forth about everything and nothing, and when we team up as duos in our games together, you feel closer to my heart than anyone has ever been.

Thank you for this incredible first month. Thank you for being my favorite duo partner, for the late-night Instagram chats where neither of us wanted to say goodnight, for sharing your world with me, and for being the person who makes me smile without even trying.

Level 1 of our story is complete, and I can't wait for every upcoming quest, every game night, and every dream we will build until the day we finally close the distance and I can hold you in person.

Happy 1-Month Anniversary, my favorite girl in the whole universe.

Forever your player 2,
Always yours.`,
  },
  milestones: [
    {
      id: 'm-1',
      title: 'First Messages on IG',
      date: 'Day 1 • Sliding Into DMs',
      description: 'The moment we sent our very first messages on Instagram. Leaving casual conversations behind and discovering how effortless, warm, and natural it felt to talk to each other right from day one.',
      iconName: 'MessageCircle',
      photoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
      x: 18,
      y: 35,
    },
    {
      id: 'm-2',
      title: 'Thinking the Same Thing',
      date: 'Day 6 • In Perfect Sync',
      description: 'The very first time we thought and said the exact same thing at the exact same moment. Realizing our minds were already synced on the same wavelength and feeling that unforgettable spark.',
      iconName: 'Heart',
      photoUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=800&auto=format&fit=crop',
      x: 34,
      y: 60,
    },
    {
      id: 'm-3',
      title: 'Duos Together',
      date: 'Day 12 • Official In-Game Duos',
      description: 'No more random teammates—from here on, we were an official duo. Clutch revives, watching each other\'s backs, sharing shields and loot, and realizing gaming is never as fun without you in my lobby.',
      iconName: 'Gamepad2',
      photoUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop',
      x: 52,
      y: 28,
    },
    {
      id: 'm-4',
      title: 'Started Talking on IG More',
      date: 'Day 20 • Reels, Stories & Late Nights',
      description: 'Instagram notifications lighting up our screens non-stop. Sending goofy reels, reacting to stories, texting back and forth, and staying up until 3:00 AM because saying goodnight was way too hard.',
      iconName: 'Moon',
      photoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800&auto=format&fit=crop',
      x: 70,
      y: 55,
    },
    {
      id: 'm-5',
      title: 'Our First Confession',
      date: 'Day 28 • Heart on My Sleeve',
      description: 'The moment feelings couldn\'t be kept as just friends or gaming buddies anymore. Heart racing through the screen, admitting how much we truly mean to each other, and taking the leap together.',
      iconName: 'Heart',
      photoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
      x: 85,
      y: 32,
    },
  ],
  memories: [
    {
      id: 'p-1',
      caption: 'In-Game Stargazing with You',
      date: 'Virtual Sunset Spot',
      imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
      note: 'Sitting our characters side-by-side watching the scenery. In every virtual world, you are the prettiest view.',
      rotation: -3,
    },
    {
      id: 'p-2',
      caption: 'Clutch Victory with My Duo',
      date: 'Ranked Adventure',
      imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
      note: 'Winning the hardest match because having you as my duo partner watching my back gives me +1000 motivation.',
      rotation: 2,
    },
    {
      id: 'p-3',
      caption: 'Late Night IG DMs & Shared Playlists',
      date: 'Our Digital Sanctuary',
      imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
      note: 'Sending each other music links, soft aesthetic posts, and laughing at reels until 3 in the morning.',
      rotation: -1.5,
    },
    {
      id: 'p-4',
      caption: 'Our Characters Side-by-Side',
      date: 'Miles Mean Nothing',
      imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop',
      note: 'Distance in kilometers means nothing when you are right there with me every single day.',
      rotation: 3.5,
    },
  ],
  reasons: [
    { id: 'r-1', category: 'smile', text: 'How cute your reactions and messages are whenever something hilarious happens in our game.' },
    { id: 'r-2', category: 'heart', text: 'How deeply caring and sweet you are, always checking if I have eaten or rested well.' },
    { id: 'r-3', category: 'comfort', text: 'Waking up to sweet good morning texts from you on Instagram and ending each day with your messages.' },
    { id: 'r-4', category: 'smile', text: 'The way you spam emojis and keyboard smashes in IG DMs whenever you find something hilarious.' },
    { id: 'r-5', category: 'comfort', text: 'How natural and effortless it feels to talk to you all day long on Instagram, sharing reels and random thoughts.' },
    { id: 'r-6', category: 'heart', text: 'How you always protect me in-game and drop me the best loot even when you need it yourself.' },
    { id: 'r-7', category: 'future', text: 'The day we finally book that flight, meet at the airport in person, and I get to hug you for real.' },
    { id: 'r-8', category: 'smile', text: 'Your sleepy good morning texts on Instagram that instantly make my day brighter.' },
    { id: 'r-9', category: 'heart', text: 'Out of all 8 billion people on Earth, and millions of gamers online, we somehow found each other.' },
    { id: 'r-10', category: 'comfort', text: 'How reading your sweet messages after a stressful day instantly melts all my anxiety away.' },
    { id: 'r-11', category: 'smile', text: 'The hilarious inside jokes that only you and I understand from our late night gaming sessions.' },
    { id: 'r-12', category: 'future', text: 'Building our cozy future gaming setup side-by-side in our own apartment one day.' },
    { id: 'r-13', category: 'heart', text: 'The pure, unconditional loyalty and affection you give me every single day.' },
    { id: 'r-14', category: 'comfort', text: 'Knowing that no matter how far apart we live right now, our hearts are completely in sync.' },
  ],
  roasts: [
    {
      id: 'roast-1',
      title: 'The 9-Damage Pump Incident',
      badge: 'Aim Accuracy: 2.1%',
      situation: 'Sneaking up behind an enemy who is standing completely still eating a medkit... You hold your mouse with intense focus, line up the crosshair on your keyboard & mouse setup, click left-click with all your might... and hit a clean 9 DAMAGE.',
      verdict: 'And then you panic and yell: "HE IS ONE! HE IS ONE REBOOT ME QUICK!"',
      iconName: 'Crosshair',
      guiltyVotes: 48,
    },
    {
      id: 'roast-2',
      title: 'LEGENDARY CHUG JUG RESERVOIR',
      badge: 'Certified Chug Thief',
      situation: 'I ping a Chug Jug so we can survive our next fight in Zero Build. You immediately drink two mini shields to reach 50, then down the entire 15-second Chug Jug all by yourself for 2 missing HP, leaving me standing there with 12 HP, 0 shield, and 2 gray bandages.',
      verdict: 'When confronted about it: "Oops I thought it was for me :3 you can eat this mushroom or use this bandage!"',
      iconName: 'ShieldAlert',
      guiltyVotes: 91,
    },
    {
      id: 'roast-3',
      title: 'Gravity: Your Undefeated Nemesis',
      badge: 'Fall Damage Royalty',
      situation: 'We are in the top 3 squads in Zero Build. Zero enemy bullets hit you all game. Then you try to slide down a gentle 4-foot grassy hill, miss the slide key on your keyboard, slip off the cliff, and get knocked to fall damage.',
      verdict: 'Gravity is currently beating you 64 to 0 this Fortnite Zero Build season.',
      iconName: 'Skull',
      guiltyVotes: 73,
    },
    {
      id: 'roast-4',
      title: 'Caught in the Open in Zero Build',
      badge: 'Zero Cover Panic',
      situation: 'A duo starts beaming us from high ground with DMRs. Since we play Zero Build and there are no builds to save you, you panic, mash every key on your keyboard, throw a Port-A-Bunker backwards, and tactical-sprint directly into a solid pine tree with your overshield completely cracked.',
      verdict: 'Mechanical keyboard RGB lights: 10/10 aesthetic. Emergency Zero Build evasive maneuvers: 0/10.',
      iconName: 'Swords',
      guiltyVotes: 79,
    },
    {
      id: 'roast-5',
      title: 'The 800-Meter Reboot Card World Tour',
      badge: 'Reboot Card Princess',
      situation: 'Dying within 45 seconds of landing at the hottest drop in Zero Build, leaving your reboot card surrounded by a sweat duo with mythic shotguns.',
      verdict: 'My official role as your duo: tactical-sprint 1,000 meters across the storm with 3 HP just to bring my favorite girl back into the lobby.',
      iconName: 'RotateCcw',
      guiltyVotes: 84,
    },
    {
      id: 'roast-6',
      title: 'Tactical Bush & Bunker Infiltration',
      badge: '0 Kills, 100% Snacks',
      situation: 'Refusing to leave a leafy bush or hide behind a rock for 14 straight minutes in Zero Build while eating snacks in real life, gently tapping your keyboard once every 3 minutes so you don\'t get AFK kicked while waiting for everyone else to eliminate each other.',
      verdict: 'Finished #2 with 0 damage dealt, 0 shots fired, and maximum emotional support.',
      iconName: 'Trophy',
      guiltyVotes: 62,
    },
    {
      id: 'roast-7',
      title: '"HE IS ONE" EARLY WARNING RADAR',
      badge: 'Said "He\'s One", Found 10',
      situation: 'You get knocked in Zero Build and scream in the mic: "HE IS ONE! HE IS ONE BRO GO GET HIM HE IS ONE!"',
      verdict: 'I slide in with high hopes only to find a full lobby of 10 people with mythic shotguns, full overshield, and 250 total health beaming me from every direction.',
      iconName: 'Flame',
      guiltyVotes: 98,
    },
    {
      id: 'roast-8',
      title: 'Still My #1 Zero Build Duo Forever',
      badge: 'Hall of Fame Duo',
      situation: 'Even if you whiff every shotgun shot, fat-finger your keyboard keys, steal the Chug Jug, and get caught with zero cover in open fields... I wouldn\'t queue up Zero Build with anyone else in the entire world.',
      verdict: 'Victory Royale or 100th place off spawn, gaming with you on keyboard is the absolute best part of my day. Forever your player 2.',
      iconName: 'Heart',
      guiltyVotes: 999,
    },
  ],
};
